[build]
builder = "nixpacks"

[deploy]
startCommand = "cd src && python -m uvicorn mcp_agent.railway_app:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "always"
restartPolicyMaxRetries = 3

[variables]
PYTHONPATH = "src"
ENVIRONMENT = "production"
MCP_PORT = "$PORT"
