[build]
builder = "dockerfile"

[deploy]
startCommand = "python -m uvicorn src.mcp_agent.railway_app:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "always"

[variables]
PYTHONPATH = "/app"
ENVIRONMENT = "production"
